# generated by datamodel-codegen:
#   filename:  active_skill_types.json
#   version:   0.28.5

from __future__ import annotations

from typing import List

from pydantic import RootModel


class Model(RootModel[List[str]]):
    root: List[str]
