# generated by datamodel-codegen:
#   filename:  active_skill_types.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import RootModel


class Model(RootModel[list[str]]):
    root: list[str]
