# generated by datamodel-codegen:
#   filename:  audio.json
#   version:   0.28.5

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, ConfigDict, RootModel


class Npc(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    name: str
    short_name: str


class AudioSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    npcs: Optional[List[Npc]] = None
    characters: Optional[List[str]] = None
    events: Optional[List[str]] = None
    text: str
    audio: Optional[List[str]] = None
    mono: Optional[str] = None
    stereo: Optional[str] = None
    video: Optional[str] = None


class Model(RootModel[Optional[Dict[str, AudioSchemaValue]]]):
    root: Optional[Dict[str, AudioSchemaValue]] = None
