# generated by datamodel-codegen:
#   filename:  audio.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel


class Npc(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    name: str
    short_name: str


class AudioSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    npcs: list[Npc] | None = None
    characters: list[str] | None = None
    events: list[str] | None = None
    text: str
    audio: list[str] | None = None
    mono: str | None = None
    stereo: str | None = None
    video: str | None = None


class Model(RootModel[dict[str, AudioSchemaValue]]):
    root: dict[str, AudioSchemaValue]
