# generated by datamodel-codegen:
#   filename:  base_items.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel
from enum import Enum


class GrantsBuff(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    stats: dict[str, int]


class Armour(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max: int
    min: int


class Requirements(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dexterity: int
    intelligence: int
    level: int
    strength: int


class VisualIdentity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dds_file: str
    id: str


class Domain(RootModel[str]):
    root: str


class ItemClass(RootModel[str]):
    root: str


class ReleaseState(Enum):
    released = "released"
    unique_only = "unique_only"
    unreleased = "unreleased"
    legacy = "legacy"


class Tag(RootModel[str]):
    root: str


class Properties(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    armour: Armour | None = None
    energy_shield: Armour | None = None
    evasion: Armour | None = None
    ward: Armour | None = None
    movement_speed: int | None = None
    block: int | None = None
    description: str | None = None
    directions: str | None = None
    stack_size: int | None = None
    stack_size_currency_tab: int | None = None
    full_stack_turns_into: str | None = None
    charges_max: int | None = None
    charges_per_use: int | None = None
    duration: int | None = None
    life_per_use: int | None = None
    mana_per_use: int | None = None
    attack_time: int | None = None
    critical_strike_chance: int | None = None
    physical_damage_max: int | None = None
    physical_damage_min: int | None = None
    range: int | None = None
    mana_burn_ms: int | None = None
    cooldown_ms: int | None = None
    monster_id: str | None = None
    monster_ability_text: str | None = None
    monster_category: str | None = None


class BaseItemsSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    domain: Domain
    drop_level: int
    implicits: list[str]
    inventory_height: int
    inventory_width: int
    inherits_from: str | None = None
    item_class: ItemClass
    name: str
    properties: Properties
    release_state: ReleaseState
    tags: list[Tag]
    visual_identity: VisualIdentity
    requirements: Requirements | None = None
    grants_buff: GrantsBuff | None = None
    skills_granted: list[str] | None = None


class Model(RootModel[dict[str, BaseItemsSchemaValue]]):
    root: dict[str, BaseItemsSchemaValue]
