# generated by datamodel-codegen:
#   filename:  buffs.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, RootModel
from enum import Enum
from typing import Literal


class Source(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str | None = None
    item: str | None = None
    name: str | None = None
    template: str | None = None
    stat_text: list[str] | None = None
    stats: dict[str, int] | None = None


class Template(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    aura_radius_metres: float | None = None
    stats: dict[str, int] | None = None
    stat_text: list[str] | None = None
    visuals: str | None = None


class Category(Enum):
    Debuff = "Debuff"
    Charge = "Charge"
    Buff = "Buff"
    Active_skill = "Active skill"
    Aspect = "Aspect"
    PVP_team = "PVP team"
    Link = "Link"
    PVP_flag = "PVP flag"
    Mark = "Mark"
    Hex = "Hex"
    Stolen = "Stolen"
    Flask = "Flask"
    Labyrinth_trap = "Labyrinth trap"
    Herald = "Herald"
    Buff_shrine = "Buff shrine"
    Spell_shrine = "Spell shrine"
    Tincture = "Tincture"
    Charm = "Charm"


class Sources(
    RootModel[
        dict[
            Literal[
                "BlightTowerAuras",
                "BlightedSporeAuras",
                "CorpseTypeTags",
                "ExplodingStormBuffs",
                "Flasks",
                "LabyrinthSecretEffects",
                "LabyrinthTrinkets",
                "Mods",
                "PassiveSkills",
                "PlayerConditions",
                "RitualRuneTypes",
                "UltimatumModifiers",
            ],
            list[Source],
        ]
    ]
):
    root: dict[
        Literal[
            "BlightTowerAuras",
            "BlightedSporeAuras",
            "CorpseTypeTags",
            "ExplodingStormBuffs",
            "Flasks",
            "LabyrinthSecretEffects",
            "LabyrinthTrinkets",
            "Mods",
            "PassiveSkills",
            "PlayerConditions",
            "RitualRuneTypes",
            "UltimatumModifiers",
        ],
        list[Source],
    ] = Field(..., title="Sources")


class BuffsSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: str
    invisible: bool
    name: str
    removable: bool
    stats: list[str]
    visuals: str
    category: Category | None = None
    sources: Sources | None = None
    templates: dict[str, Template] | None = None
    stack_limit: int | None = None


class Model(RootModel[dict[str, BuffsSchemaValue]]):
    root: dict[str, BuffsSchemaValue]
