# generated by datamodel-codegen:
#   filename:  buff_visuals.json
#   version:   0.75.1

from __future__ import annotations
from enum import Enum
from pydantic import BaseModel, ConfigDict, Field, RootModel
from typing import Literal


class Category(Enum):
    Debuff = "Debuff"
    Charge = "Charge"
    Buff = "Buff"
    Active_skill = "Active skill"
    Aspect = "Aspect"
    PVP_team = "PVP team"
    Link = "Link"
    PVP_flag = "PVP flag"
    Mark = "Mark"
    Hex = "Hex"
    Stolen = "Stolen"
    Flask = "Flask"
    Labyrinth_trap = "Labyrinth trap"
    Herald = "Herald"
    Buff_shrine = "Buff shrine"
    Spell_shrine = "Spell shrine"
    Tincture = "Tincture"
    Charm = "Charm"


class Source(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str | None = None
    buff_id: str | None = None
    buff_category: Category | None = None
    item: str | None = None
    description: str | None = None
    name: str | None = None


class Sources(
    RootModel[
        dict[
            Literal["BuffDefinitions", "BuffTemplates", "ExplodingStormBuffs", "LegionFactions", "DroneBaseTypes"],
            list[Source],
        ]
    ]
):
    root: dict[
        Literal["BuffDefinitions", "BuffTemplates", "ExplodingStormBuffs", "LegionFactions", "DroneBaseTypes"],
        list[Source],
    ] = Field(..., title="Sources")


class BuffVisualsSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: str | None = None
    icon: str | None = None
    name: str | None = None
    sources: Sources | None = None
    sounds: list[str] | None = None
    custom_frame: str | None = None


class Model(RootModel[dict[str, BuffVisualsSchemaValue]]):
    root: dict[str, BuffVisualsSchemaValue]
