# generated by datamodel-codegen:
#   filename:  cluster_jewel_notables.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel


class ClusterJewelNotablesSchemaElement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    jewel_stat: str
    name: str


class Model(RootModel[list[ClusterJewelNotablesSchemaElement]]):
    root: list[ClusterJewelNotablesSchemaElement]
