# generated by datamodel-codegen:
#   filename:  cluster_jewels.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, RootModel
from enum import Enum


class PassiveSkill(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    name: str
    stats: dict[str, int]
    stat_text: list[str]
    tag: str


class MetadataItemsJewelsJewelPassiveTreeExpansionLargeSize(Enum):
    Large = "Large"


class MetadataItemsJewelsJewelPassiveTreeExpansionMediumSize(Enum):
    Medium = "Medium"


class MetadataItemsJewelsJewelPassiveTreeExpansionSmallSize(Enum):
    Small = "Small"


class MetadataItemsJewelsJewelPassiveTreeExpansionLarge(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_skills: int
    min_skills: int
    name: str
    notable_indices: list[int]
    passive_skills: list[PassiveSkill]
    size: MetadataItemsJewelsJewelPassiveTreeExpansionLargeSize
    small_indices: list[int]
    socket_indices: list[int]
    total_indices: int


class MetadataItemsJewelsJewelPassiveTreeExpansionMedium(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_skills: int
    min_skills: int
    name: str
    notable_indices: list[int]
    passive_skills: list[PassiveSkill]
    size: MetadataItemsJewelsJewelPassiveTreeExpansionMediumSize
    small_indices: list[int]
    socket_indices: list[int]
    total_indices: int


class MetadataItemsJewelsJewelPassiveTreeExpansionSmall(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_skills: int
    min_skills: int
    name: str
    notable_indices: list[int]
    passive_skills: list[PassiveSkill]
    size: MetadataItemsJewelsJewelPassiveTreeExpansionSmallSize
    small_indices: list[int]
    socket_indices: list[int]
    total_indices: int


class ClusterJewelsSchema(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Metadata_Items_Jewels_JewelPassiveTreeExpansionLarge: MetadataItemsJewelsJewelPassiveTreeExpansionLarge = Field(
        ..., alias="Metadata/Items/Jewels/JewelPassiveTreeExpansionLarge"
    )
    Metadata_Items_Jewels_JewelPassiveTreeExpansionMedium: MetadataItemsJewelsJewelPassiveTreeExpansionMedium = Field(
        ..., alias="Metadata/Items/Jewels/JewelPassiveTreeExpansionMedium"
    )
    Metadata_Items_Jewels_JewelPassiveTreeExpansionSmall: MetadataItemsJewelsJewelPassiveTreeExpansionSmall = Field(
        ..., alias="Metadata/Items/Jewels/JewelPassiveTreeExpansionSmall"
    )


class Model(RootModel[ClusterJewelsSchema]):
    root: ClusterJewelsSchema
