# generated by datamodel-codegen:
#   filename:  cost_types.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel


class CostTypesSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    format_text: str
    stat: str


class Model(RootModel[dict[str, CostTypesSchemaValue]]):
    root: dict[str, CostTypesSchemaValue]
