# generated by datamodel-codegen:
#   filename:  cost_types.schema.json
#   version:   0.28.5

from __future__ import annotations

from typing import Dict, Optional

from pydantic import BaseModel, ConfigDict, RootModel


class CostTypesSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    format_text: str
    stat: str


class Model(RootModel[Optional[Dict[str, CostTypesSchemaValue]]]):
    root: Optional[Dict[str, CostTypesSchemaValue]] = None
