# generated by datamodel-codegen:
#   filename:  default_monster_stats.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel


class DefaultMonsterStatsSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accuracy: int
    ally_life: int
    armour: int
    evasion: int
    life: int
    experience: int | None = None
    physical_damage: float


class Model(RootModel[dict[str, DefaultMonsterStatsSchemaValue]]):
    root: dict[str, DefaultMonsterStatsSchemaValue]
