# generated by datamodel-codegen:
#   filename:  essences.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, RootModel


class Type(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    is_corruption_only: bool
    tier: int


class EssenceMods(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Amulet: str | None = None
    Belt: str | None = None
    Body_Armour: str | None = Field(None, alias="Body Armour")
    Boots: str | None = None
    Bow: str | None = None
    Claw: str | None = None
    Dagger: str | None = None
    Gloves: str | None = None
    Helmet: str | None = None
    One_Hand_Axe: str | None = Field(None, alias="One Hand Axe")
    One_Hand_Mace: str | None = Field(None, alias="One Hand Mace")
    One_Hand_Sword: str | None = Field(None, alias="One Hand Sword")
    Quiver: str | None = None
    Ring: str | None = None
    Sceptre: str | None = None
    Shield: str | None = None
    Staff: str | None = None
    Thrusting_One_Hand_Sword: str | None = Field(None, alias="Thrusting One Hand Sword")
    Two_Hand_Axe: str | None = Field(None, alias="Two Hand Axe")
    Two_Hand_Mace: str | None = Field(None, alias="Two Hand Mace")
    Two_Hand_Sword: str | None = Field(None, alias="Two Hand Sword")
    Wand: str | None = None


class Essence(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    item_level_restriction: int | None = None
    level: int
    mods: EssenceMods | None = None
    name: str
    spawn_level_min: int
    type: Type


class EssencesSchema(RootModel[dict[str, Essence]]):
    root: dict[str, Essence]


class Model(RootModel[EssencesSchema]):
    root: EssencesSchema
