# generated by datamodel-codegen:
#   filename:  flavour.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import RootModel


class Model(RootModel[dict[str, str]]):
    root: dict[str, str]
