# generated by datamodel-codegen:
#   filename:  fossils.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel


class TiveModWeight(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tag: str
    weight: int


class FossilsSchema1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    added_mods: list[str]
    allowed_tags: list[str]
    blocked_descriptions: dict[str, str]
    changes_quality: bool
    corrupted_essence_chance: int
    descriptions: dict[str, str]
    forbidden_tags: list[str]
    forced_mods: list[str]
    mirrors: bool
    name: str
    negative_mod_weights: list[TiveModWeight]
    positive_mod_weights: list[TiveModWeight]
    rolls_lucky: bool
    rolls_white_sockets: bool
    sell_price_mods: list[str]


class FossilsSchema(RootModel[dict[str, FossilsSchema1]]):
    root: dict[str, FossilsSchema1]


class Model(RootModel[FossilsSchema]):
    root: FossilsSchema
