# generated by datamodel-codegen:
#   filename:  gem_tags.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import RootModel


class GemTagsSchema(RootModel[dict[str, str | None]]):
    root: dict[str, str | None]


class Model(RootModel[GemTagsSchema]):
    root: GemTagsSchema
