# generated by datamodel-codegen:
#   filename:  gems_minimal.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel
from typing import Any
from enum import Enum


class Costs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Mana: int | None = None
    ManaPercent: int | None = None
    ManaPercentPerMinute: int | None = None


class QualityStat(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    stat: str
    stats: dict[str, int]


class Reservations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mana_percent: float | None = None
    mana_flat: int | None = None


class StatRequirements(BaseModel):
    int: Any | None = None
    str: Any | None = None
    dex: Any | None = None


class Vaal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    souls: int
    stored_uses: int


class MinionTypeElement(RootModel[str]):
    root: str


class WeaponRestriction(RootModel[str]):
    root: str


class ExperienceType(RootModel[str]):
    root: str


class ReleaseState(Enum):
    released = "released"
    unreleased = "unreleased"
    legacy = "legacy"


class Color(Enum):
    b = "b"
    r = "r"
    g = "g"
    w = "w"


class Discriminator(Enum):
    alt_x = "alt_x"
    alt_y = "alt_y"


class Class(RootModel[str]):
    root: str


class StatTranslationFile(RootModel[str]):
    root: str


class CooldownBypassType(Enum):
    expend_frenzy_charge = "expend_frenzy_charge"
    expend_power_charge = "expend_power_charge"
    expend_endurance_charge = "expend_endurance_charge"


class StatType(Enum):
    float = "float"
    constant = "constant"
    additional = "additional"
    implicit = "implicit"
    flag = "flag"


class Tag(RootModel[str]):
    root: str


class ActiveSkill(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: str
    display_name: str
    id: str
    is_manually_casted: bool
    is_skill_totem: bool
    stat_conversions: dict[str, str]
    types: list[MinionTypeElement]
    weapon_restrictions: list[WeaponRestriction]
    minion_types: list[MinionTypeElement] | None = None
    skill_totem_life_multiplier: float | None = None


class BaseItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    display_name: str
    experience_type: ExperienceType
    id: str
    max_level: int
    release_state: ReleaseState


class QuestReward(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    act: int
    classes: list[Class]
    quest: str


class Stat(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str | None = None
    type: StatType
    value: int | None = None


class SupportGem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    allowed_types: list[MinionTypeElement] | None = None
    letter: str
    supports_gems_only: bool
    support_name: str | None = None
    support_text: str | None = None
    excluded_types: list[MinionTypeElement] | None = None
    added_types: list[MinionTypeElement] | None = None
    added_minion_types: list[MinionTypeElement] | None = None


class Static(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    crit_chance: int | None = None
    damage_effectiveness: int | None = None
    quality_stats: list[QualityStat]
    stat_requirements: StatRequirements | None = None
    stat_text: dict[str, str] | None = None
    stats: list[Stat | None] | None = None
    vaal: Vaal | None = None
    costs: Costs | None = None
    attack_speed_multiplier: int | None = None
    cooldown: int | None = None
    stored_uses: int | None = None
    cost_multiplier: int | None = None
    cooldown_bypass_type: CooldownBypassType | None = None
    required_level: int | None = None
    experience: int | None = None
    reservations: Reservations | None = None
    damage_multiplier: int | None = None


class GemsMinimalSchemaElement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    active_skill: ActiveSkill | None = None
    base_item: BaseItem
    cast_time: int | None = None
    color: Color
    display_name: str
    is_support: bool
    stat_translation_file: StatTranslationFile
    static: Static
    tooltip_order: list[str] | None = None
    tags: list[Tag]
    secondary_granted_effect: str | None = None
    quest_reward: QuestReward | None = None
    discriminator: Discriminator | None = None
    support_gem: SupportGem | None = None


class Model(RootModel[list[GemsMinimalSchemaElement]]):
    root: list[GemsMinimalSchemaElement]
