# generated by datamodel-codegen:
#   filename:  gems.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel
from typing import Any
from enum import Enum


class Costs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Mana: int | None = None
    Life: int | None = None
    ManaPerMinute: int | None = None
    ManaPercent: int | None = None
    ManaPercentPerMinute: int | None = None
    ES: int | None = None


class PerLevelReservations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mana_flat: int | None = None
    mana_percent: float | None = None


class StatRequirements(BaseModel):
    int: Any | None = None
    str: Any | None = None
    dex: Any | None = None


class QualityStat(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    stat: str
    stats: dict[str, int]


class StaticReservations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mana_percent: float | None = None
    life_percent: float | None = None
    mana_flat: int | None = None


class Vaal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    souls: int
    stored_uses: int


class MinionTypeElement(RootModel[str]):
    root: str


class WeaponRestriction(RootModel[str]):
    root: str


class ExperienceType(RootModel[str]):
    root: str


class ReleaseState(Enum):
    released = "released"
    unreleased = "unreleased"
    legacy = "legacy"


class Color(Enum):
    r = "r"
    g = "g"
    w = "w"
    b = "b"


class Discriminator(Enum):
    alt_x = "alt_x"
    alt_y = "alt_y"


class StatType(Enum):
    float = "float"
    constant = "constant"
    additional = "additional"
    implicit = "implicit"
    flag = "flag"


class Class(RootModel[str]):
    root: str


class StatTranslationFile(RootModel[str]):
    root: str


class CooldownBypassType(Enum):
    expend_frenzy_charge = "expend_frenzy_charge"
    expend_power_charge = "expend_power_charge"
    expend_endurance_charge = "expend_endurance_charge"


class Tag(RootModel[str]):
    root: str


class ActiveSkill(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: str
    display_name: str
    id: str
    is_manually_casted: bool
    is_skill_totem: bool
    stat_conversions: dict[str, str]
    types: list[MinionTypeElement] | None = None
    weapon_restrictions: list[WeaponRestriction]
    skill_totem_life_multiplier: float | None = None
    minion_types: list[MinionTypeElement] | None = None


class BaseItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    display_name: str
    experience_type: ExperienceType
    id: str
    max_level: int
    release_state: ReleaseState


class Stat(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    value: int | None = None
    id: str | None = None
    type: StatType | None = None


class QuestReward(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    act: int
    classes: list[Class]
    quest: str


class Static(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    crit_chance: int | None = None
    damage_effectiveness: int | None = None
    quality_stats: list[QualityStat]
    stat_requirements: StatRequirements | None = None
    stat_text: dict[str, str] | None = None
    stats: list[Stat | None] | None = None
    cooldown: int | None = None
    stored_uses: int | None = None
    required_level: int | None = None
    attack_speed_multiplier: int | None = None
    costs: Costs | None = None
    cost_multiplier: int | None = None
    reservations: StaticReservations | None = None
    experience: int | None = None
    damage_multiplier: int | None = None
    vaal: Vaal | None = None
    cooldown_bypass_type: CooldownBypassType | None = None


class SupportGem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    allowed_types: list[MinionTypeElement] | None = None
    excluded_types: list[MinionTypeElement] | None = None
    letter: str
    supports_gems_only: bool
    support_name: str | None = None
    support_text: str | None = None
    added_types: list[MinionTypeElement] | None = None
    added_minion_types: list[MinionTypeElement] | None = None


class PerLevel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    costs: Costs | None = None
    experience: int | None = None
    required_level: int | None = None
    stat_requirements: StatRequirements | None = None
    stat_text: dict[str, str] | None = None
    stats: list[Stat | None] | None = None
    reservations: PerLevelReservations | None = None
    damage_effectiveness: int | None = None
    damage_multiplier: int | None = None
    cooldown: int | None = None
    cost_multiplier: int | None = None
    stored_uses: int | None = None


class GemsSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    active_skill: ActiveSkill | None = None
    base_item: BaseItem | None = None
    cast_time: int | None = None
    color: Color
    display_name: str | None = None
    is_support: bool
    per_level: dict[str, PerLevel]
    quest_reward: QuestReward | None = None
    stat_translation_file: StatTranslationFile
    static: Static
    tags: list[Tag] | None = None
    tooltip_order: list[str] | None = None
    discriminator: Discriminator | None = None
    secondary_granted_effect: str | None = None
    support_gem: SupportGem | None = None


class Model(RootModel[dict[str, GemsSchemaValue]]):
    root: dict[str, GemsSchemaValue]
