# generated by datamodel-codegen:
#   filename:  item_classes.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel


class ItemClassesSchema1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    category: str | None = None
    category_id: str | None = None
    name: str
    influence_tags: list[str] | None = None


class ItemClassesSchema(RootModel[dict[str, ItemClassesSchema1]]):
    root: dict[str, ItemClassesSchema1]


class Model(RootModel[ItemClassesSchema]):
    root: ItemClassesSchema
