# generated by datamodel-codegen:
#   filename:  lab_layout.json
#   version:   0.75.1

from __future__ import annotations
from enum import Enum
from pydantic import BaseModel, ConfigDict, RootModel


class Group(Enum):
    MandatoryGoldDoor = "MandatoryGoldDoor"


class Override(Enum):
    BottleneckOverride = "BottleneckOverride"
    Weylin03 = "Weylin03"
    Weylin04 = "Weylin04"
    FinalBossEasy = "FinalBossEasy"
    FinalBoss = "FinalBoss"
    AirlockEntry = "AirlockEntry"
    Boss1_Sec1 = "Boss1_Sec1"
    Boss2_Sec1 = "Boss2_Sec1"
    Weylin01 = "Weylin01"
    Weylin02 = "Weylin02"
    Boss2_Sec2 = "Boss2_Sec2"
    Boss1_Sec2 = "Boss1_Sec2"


class Secret(Enum):
    SilverKey = "SilverKey"
    SilverDoorReward = "SilverDoorReward"
    GoldKey = "GoldKey"
    GoldDoor = "GoldDoor"
    Gauntlet = "Gauntlet"
    GoldDoorModal = "GoldDoorModal"
    Trinket = "Trinket"


class Room(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    areas: list[str]
    connections: list[int]
    override: Override | None = None
    row_id: int
    x: float
    y: float
    secret_1: Secret | None = None
    secret_2: Secret | None = None


class Section(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    difficulty: int
    rooms: list[Room]
    section: int
    group: Group | None = None


class LabLayoutSchema(RootModel[dict[str, Section]]):
    root: dict[str, Section]


class Model(RootModel[LabLayoutSchema]):
    root: LabLayoutSchema
