# generated by datamodel-codegen:
#   filename:  mercenary_flavour_text.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel


class TagWeight(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tag: str
    weight: int


class MercenaryFlavourTextSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: str
    tag_weights: list[TagWeight]


class Model(RootModel[dict[str, MercenaryFlavourTextSchemaValue]]):
    root: dict[str, MercenaryFlavourTextSchemaValue]
