# generated by datamodel-codegen:
#   filename:  mercenary_inventories.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel


class MercenaryInventoriesSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    position_x: int
    position_y: int


class Model(RootModel[dict[str, MercenaryInventoriesSchemaValue]]):
    root: dict[str, MercenaryInventoriesSchemaValue]
