# generated by datamodel-codegen:
#   filename:  mercenary_skills.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel
from enum import Enum


class ActiveSkill(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    display_name: str
    description: str
    types: list[str] | None = None
    weapon_restrictions: list[str]
    is_skill_totem: bool
    is_manually_casted: bool
    stat_conversions: dict[str, str]
    skill_totem_life_multiplier: float | None = None
    minion_types: list[str] | None = None


class StatType(Enum):
    float = "float"
    constant = "constant"
    additional = "additional"
    implicit = "implicit"
    flag = "flag"


class QualityStat(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    stat: str
    stats: dict[str, int]


class Reservations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mana_flat: int | None = None
    mana_percent: float | None = None
    life_flat: int | None = None
    life_percent: float | None = None


class Vaal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    souls: int
    stored_uses: int


class Stat(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str | None = None
    value: int | None = None
    type: StatType | None = None


class SkillLevel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    experience: int | None = None
    required_level: int | None = None
    cooldown: int | None = None
    cooldown_bypass_type: str | None = None
    stored_uses: int | None = None
    cost_multiplier: int | None = None
    costs: dict[str, int] | None = None
    damage_effectiveness: int | None = None
    damage_multiplier: int | None = None
    crit_chance: int | None = None
    attack_speed_multiplier: int | None = None
    vaal: Vaal | None = None
    reservations: Reservations | None = None
    stats: list[Stat | None] | None = None
    stat_text: dict[str, str] | None = None
    quality_stats: list[QualityStat] | None = None


class MercenarySkillsSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    description: str
    required_level: int
    support_count: str | None = None
    possible_supports: list[str]
    family: str | None = None
    encounter_granted_effect: str | None = None
    house_icon: str
    icon: str | None = None
    cast_time: int | None = None
    active_skill: ActiveSkill | None = None
    stat_translation_file: str | None = None
    per_level: dict[str, SkillLevel] | None = None
    static: SkillLevel | None = None
    tooltip_order: list[str] | None = None


class Model(RootModel[dict[str, MercenarySkillsSchemaValue]]):
    root: dict[str, MercenarySkillsSchemaValue]
