# generated by datamodel-codegen:
#   filename:  mercenary_classes.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel


class Attribute(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    name: str
    tags: list[str]


class MercenaryClassesSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    house_name: str
    attribute: Attribute
    monster_variety: str | None = None
    monster_variety_allied: str | None = None
    terrain_feature: str | None = None
    house_spawn_chance_stats: list[str]
    attribute_spawn_chance_stats: list[str]
    class_icon: str
    house_icon: str
    house_buff_icon: str


class Model(RootModel[dict[str, MercenaryClassesSchemaValue]]):
    root: dict[str, MercenaryClassesSchemaValue]
