# generated by datamodel-codegen:
#   filename:  mercenary_supports.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel


class Stat(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    value: int


class MercenarySupportsSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    tier: int
    family: str | None = None
    icon: str
    stats: list[Stat]
    stat_text: dict[str, str]


class Model(RootModel[dict[str, MercenarySupportsSchemaValue]]):
    root: dict[str, MercenarySupportsSchemaValue]
