# generated by datamodel-codegen:
#   filename:  mercenary_builds.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel


class SkillPool(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    count: int
    pool: list[str]


class ExtraStatCategory(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    name: str


class VisualOverride(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    slot_id: int
    mtx_type: str | None = None
    dds_file: str | None = None


class ExtraStat(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    stat_id: str
    level24: int
    level68: int
    level84: int
    category: ExtraStatCategory | None = None


class MercenaryBuildsSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    class_id: str
    is_infamous: bool
    primary_skills: list[str]
    secondary_skills: SkillPool
    utility_skills: SkillPool
    idle_skill: str | None = None
    tags: list[str]
    weapon_item_classes: list[str]
    extra_stats: list[ExtraStat]
    achievements: list[str]
    visual_overrides: list[VisualOverride]
    ai_file: str


class Model(RootModel[dict[str, MercenaryBuildsSchemaValue]]):
    root: dict[str, MercenaryBuildsSchemaValue]
