# generated by datamodel-codegen:
#   filename:  mod_types.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel


class ModTypesSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sell_price_types: list[str]


class Model(RootModel[dict[str, ModTypesSchemaValue]]):
    root: dict[str, ModTypesSchemaValue]
