# generated by datamodel-codegen:
#   filename:  mods_by_base.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, RootModel


class ModWeights(RootModel[dict[str, int]]):
    root: dict[str, int]


class SynthModGroups(RootModel[dict[str, list[str]]]):
    root: dict[str, list[str]]


class EssenceMods(RootModel[dict[str, str]]):
    root: dict[str, str]


class ModTypes(RootModel[dict[str, ModWeights]]):
    root: dict[str, ModWeights]


class EssenceModLevels(RootModel[dict[str, EssenceMods]]):
    root: dict[str, EssenceMods]


class GenerationTypes(RootModel[dict[str, ModTypes]]):
    root: dict[str, ModTypes]


class TagSet(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bases: list[str]
    mods: GenerationTypes
    conditional_mods: list[str] | None = Field(
        None,
        description="Lists all mods that spawn (or don't spawn) at different weights depending on the presence or absence of other mods on the base.",
    )


class TagSets(RootModel[dict[str, TagSet | SynthModGroups | EssenceModLevels]]):
    root: dict[str, TagSet | SynthModGroups | EssenceModLevels]


class ItemClasses(RootModel[dict[str, TagSets]]):
    root: dict[str, TagSets]


class Model(RootModel[ItemClasses]):
    root: ItemClasses
