# generated by datamodel-codegen:
#   filename:  mods.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel


class GrantsEffect(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    granted_effect_id: str
    level: int


class Stat(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    max: int
    min: int


class AddsTag(RootModel[str]):
    root: str


class Domain(RootModel[str]):
    root: str


class GenerationType(RootModel[str]):
    root: str


class Tag(RootModel[str]):
    root: str


class ImplicitTag(RootModel[str]):
    root: str


class NWeight(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tag: Tag
    weight: int


class ModsSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    adds_tags: list[AddsTag]
    domain: Domain
    generation_type: GenerationType
    generation_weights: list[NWeight]
    grants_effects: list[GrantsEffect]
    groups: list[str]
    implicit_tags: list[ImplicitTag]
    is_essence_only: bool
    name: str
    required_level: int
    spawn_weights: list[NWeight]
    stats: list[Stat]
    text: str | None = None
    type: str
    gold_value: float | None = None


class Model(RootModel[dict[str, ModsSchemaValue]]):
    root: dict[str, ModsSchemaValue]
