# generated by datamodel-codegen:
#   filename:  stats.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel


class Alias(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    when_in_off_hand: str | None = None
    when_in_main_hand: str | None = None


class StatsSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    alias: Alias
    is_aliased: bool
    is_local: bool


class Model(RootModel[dict[str, StatsSchemaValue]]):
    root: dict[str, StatsSchemaValue]
