# generated by datamodel-codegen:
#   filename:  stat_translations.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, RootModel
from enum import Enum


class Condition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    min: int | None = None
    max: int | None = None
    negated: bool | None = None


class OptionElement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: int
    text: str


class Format(Enum):
    ignore = "ignore"
    field_ = "#"
    field__ = "+#"


class IndexHandler(RootModel[str]):
    root: str


class Type(RootModel[str]):
    root: str


class Stat(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    condition: list[Condition]
    format: list[Format]
    index_handlers: list[list[IndexHandler]]
    string: str
    reminder_text: str | None = None
    is_markup: bool | None = None


class TradeStatOption(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    options: list[OptionElement]


class TradeStat(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    text: str
    type: Type
    option: TradeStatOption | None = None


class StatTranslationsSchemaElement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    English: list[Stat] | None = None
    ids: list[str]
    trade_stats: list[TradeStat] | None = None
    hidden: bool | None = None
    French: list[Stat] | None = None
    German: list[Stat] | None = None
    Japanese: list[Stat] | None = None
    Korean: list[Stat] | None = None
    Portuguese: list[Stat] | None = None
    Russian: list[Stat] | None = None
    Spanish: list[Stat] | None = None
    Thai: list[Stat] | None = None
    Traditional_Chinese: list[Stat] | None = Field(None, alias="Traditional Chinese")


class Model(RootModel[list[StatTranslationsSchemaElement]]):
    root: list[StatTranslationsSchemaElement]
