# generated by datamodel-codegen:
#   filename:  stat_value_handlers.json
#   version:   0.75.1

from __future__ import annotations
from enum import Enum
from pydantic import BaseModel, ConfigDict, Field, RootModel


class Type(Enum):
    int = "int"


class IntHandler(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    addend: float | None = None
    divisor: float | None = None
    multiplier: float | None = None
    precision: int | None = None
    fixed: bool | None = None
    type: Type


class Type1(Enum):
    relational = "relational"


class Predicate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    column: str | None = None
    value: int | None = None


class Type2(Enum):
    string = "string"


class CanonicalLine(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type2


class Type3(Enum):
    noop = "noop"


class Noop(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type3


class RelationalData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dat_file: str
    index_column: str | None = None
    type: Type1
    value_column: str
    values: dict[str, str] = Field(..., description="Map from integer stat values to text associated with that value")
    predicate: Predicate | None = None


class Model(RootModel[dict[str, IntHandler | RelationalData | CanonicalLine | Noop]]):
    root: dict[str, IntHandler | RelationalData | CanonicalLine | Noop]
