# generated by datamodel-codegen:
#   filename:  uniques_poewiki.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel


class UniquesPoewikiSchemaElement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    base_item: str
    base_item_id: str | None = None
    cannot_be_traded_or_modified: bool
    description: str | None = None
    drop_enabled: bool
    is_account_bound: bool
    is_corrupted: bool
    is_drop_restricted: bool
    is_eater_of_worlds_item: bool
    is_fractured: bool
    is_in_game: bool
    is_replica: bool
    is_searing_exarch_item: bool
    is_synthesised: bool
    is_unmodifiable: bool
    is_veiled: bool
    item_class: str
    item_class_id: str
    name: str
    name_list: str
    page_name: str
    release_version: str | None = None
    required_dexterity: int | None = None
    required_intelligence: int | None = None
    required_level: int
    required_strength: int | None = None
    tags: str
    drop_monsters: str | None = None
    drop_text: str | None = None
    drop_level: int | None = None
    acquisition_tags: str | None = None
    drop_areas: str | None = None
    removal_version: str | None = None
    influences: str | None = None
    is_relic: bool | None = None


class Model(RootModel[dict[str, list[UniquesPoewikiSchemaElement]]]):
    root: dict[str, list[UniquesPoewikiSchemaElement]]
