# generated by datamodel-codegen:
#   filename:  world_area_graph.json
#   version:   0.28.5

from __future__ import annotations

from typing import Dict, List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Data(BaseModel):
    Default_: Optional[List[int]] = Field(None, alias="Default%")
    MasterFile: str


class EdgeTypes(BaseModel):
    pass
    model_config = ConfigDict(
        extra="forbid",
    )


class EdgeType(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    color: Optional[str] = None


class FillTile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file: str
    prefix: Optional[List[int]] = None
    tile_tgt: Optional[str] = None


class Master(BaseModel):
    ChestData: Optional[str] = None
    Doodads: Optional[str] = None
    EdgeCombination: Optional[str] = None
    FillTiles: Optional[str] = None
    MaterialsList: Optional[str] = None
    OuterGroundType: Optional[str] = None
    Reskin: Optional[str] = None
    RoomSet: Optional[str] = None
    TileSet: Optional[str] = None
    version: Optional[int] = None
    StoreyHeight: Optional[int] = None
    RoomUnitSize: Optional[int] = None
    RoomOverlap: Optional[Union[int, List[int]]] = None
    OuterBufferSize: Optional[Union[int, List[int]]] = None
    EdgePoints: Optional[str] = None
    Decals: Optional[str] = None
    Overlays: Optional[str] = None
    RestrictedGTs: Optional[str] = None
    EnvironmentPreload: Optional[str] = None
    Critters: Optional[str] = None
    FileGroups: Optional[str] = None


class TileSet(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file: str
    prefix: Optional[List[int]] = None
    tile_tag: Optional[str] = None
    suffix: Optional[List] = None


class TileParent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file: str
    tile_parent: Optional[TileParent] = None
    tile_tag: Optional[str] = None
    tile_tgt: Optional[str] = None


class Unknown(RootModel[Union[int, str]]):
    root: Union[int, str] = Field(..., title="Unknown")


class Edge(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_: int = Field(..., alias="from")
    to: int
    path: List[List[int]]
    unknown: List[Unknown]
    edge_type: Optional[str] = None
    color: Optional[str] = None


class FileSetItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file: str
    prefix: Optional[List[str]] = None
    suffix: Optional[List[str]] = None
    tile_tag: Optional[str] = None
    room_tag: Optional[str] = None
    tile_tgt: Optional[str] = None
    tile_parent: Optional[TileParent] = None


class Node(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    numbers: List[int]
    room: str
    strings: List[str]
    transform: str
    unknown: List[Unknown]
    x: int
    y: int


class WorldAreaGraph(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Data
    edge_count: int
    edge_types: Dict[str, EdgeType]
    edges: List[Edge]
    fill_tiles: Optional[List[FileSetItem]] = None
    master: Master
    node_count: int
    numbers: Optional[List[int]] = None
    nodes: List[Node]
    room_set: Optional[List[FileSetItem]] = None
    size: List[int]
    strings: List[str]
    tile_set: Optional[List[FileSetItem]] = None
    version: int
    subgraphs: Optional[Dict[str, List[str]]] = None
    file_groups: Optional[Dict[str, List[str]]] = None


class Model(RootModel[WorldAreaGraph]):
    root: WorldAreaGraph


TileParent.model_rebuild()
