# generated by datamodel-codegen:
#   filename:  world_area_graph.json
#   version:   0.28.5

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Data(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Default_: List[int] = Field(..., alias="Default%")
    MasterFile: str


class EdgeTypes(BaseModel):
    pass
    model_config = ConfigDict(
        extra="forbid",
    )


class FillTile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file: str
    prefix: Optional[List[int]] = None
    tile_tgt: Optional[str] = None


class Master(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ChestData: str
    Doodads: str
    EdgeCombination: str
    FillTiles: str
    MaterialsList: str
    OuterGroundType: str
    Reskin: str
    RoomSet: str
    TileSet: str


class TileSet(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file: str
    prefix: Optional[List[int]] = None
    tile_tag: Optional[str] = None
    suffix: Optional[List] = None


class Unknown(RootModel[Union[int, str]]):
    root: Union[int, str] = Field(..., title="Unknown")


class Node(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    numbers: List
    room: str
    strings: List[str]
    transform: str
    unknown: List[Unknown]
    x: int
    y: int


class WorldAreaGraph(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Data
    edge_count: int
    edge_types: EdgeTypes
    edges: List
    fill_tiles: List[FillTile]
    master: Master
    node_count: int
    nodes: List[Node]
    room_set: List
    size: List[int]
    strings: List[str]
    tile_set: List[TileSet]
    version: int


class Model(RootModel[WorldAreaGraph]):
    root: WorldAreaGraph
