# generated by datamodel-codegen:
#   filename:  world_area_graph.json
#   version:   0.75.1

from __future__ import annotations
from typing import Any, Dict
from pydantic import BaseModel, ConfigDict, Field, RootModel


class Data(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    __annotations__ = {
        "__pydantic_extra__": Dict[str, str | int | list[int]],
    }
    Default_: list[int] | None = Field(None, alias="Default%")
    MasterFile: str


class EdgeTypes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )


class EdgeType(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    color: str | None = None


class FillTile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file: str
    prefix: list[int] | None = None
    tile_tgt: str | None = None


class Master(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    __annotations__ = {
        "__pydantic_extra__": Dict[str, str | int | list[int]],
    }
    ChestData: str | None = None
    Doodads: str | None = None
    EdgeCombination: str | None = None
    FillTiles: str | None = None
    MaterialsList: str | None = None
    OuterGroundType: str | None = None
    Reskin: str | None = None
    RoomSet: str | None = None
    TileSet: str | None = None
    version: int | None = None
    StoreyHeight: int | None = None
    RoomUnitSize: int | None = None
    RoomOverlap: int | list[int] | None = None
    OuterBufferSize: int | list[int] | None = None
    EdgePoints: str | None = None
    Decals: str | None = None
    Overlays: str | None = None
    RestrictedGTs: str | None = None
    EnvironmentPreload: str | None = None
    Critters: str | None = None
    FileGroups: str | None = None


class TileSet(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file: str
    prefix: list[int] | None = None
    tile_tag: str | None = None
    suffix: list[Any] | None = None


class TileParent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file: str
    tile_parent: TileParent | None = None
    tile_tag: str | None = None
    tile_tgt: str | None = None


class Unknown(RootModel[int | str]):
    root: int | str = Field(..., title="Unknown")


class Edge(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_: int = Field(..., alias="from")
    to: int
    path: list[list[int]]
    unknown: list[Unknown]
    edge_type: str | None = None
    color: str | None = None


class FileSetItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file: str
    prefix: list[str] | None = None
    suffix: list[str] | None = None
    tile_tag: str | None = None
    room_tag: str | None = None
    tile_tgt: str | None = None
    tile_parent: TileParent | None = None


class Node(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    numbers: list[int]
    room: str
    strings: list[str]
    transform: str
    unknown: list[Unknown]
    x: int
    y: int


class WorldAreaGraph(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Data
    edge_count: int
    edge_types: dict[str, EdgeType]
    edges: list[Edge]
    fill_tiles: list[FileSetItem] | None = None
    master: Master
    node_count: int
    numbers: list[int] | None = None
    nodes: list[Node]
    room_set: list[FileSetItem] | None = None
    size: list[int]
    strings: list[str]
    tile_set: list[FileSetItem] | None = None
    version: int
    subgraphs: dict[str, list[str]] | None = None
    file_groups: dict[str, list[str]] | None = None


class Model(RootModel[WorldAreaGraph]):
    root: WorldAreaGraph


TileParent.model_rebuild()
