# generated by datamodel-codegen:
#   filename:  world_areas.json
#   version:   0.75.1

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, RootModel


class AdditionalMonster(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    count: int


class Monster(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    monster_variety: str | None = None
    flag: bool
    weight: int


class Topology(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    file: str
    id: str


class Pack(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    additional_monsters: dict[str, AdditionalMonster] | None = None
    boss_chance: int
    boss_count: int
    boss_monster_spawn_chance: int | None = None
    boss_monsters: list[str] | None = None
    id: str
    max_count: int
    min_count: int
    monsters: dict[str, Monster] | None = None
    tags: list[str]
    formation: str | None = None


class WorldAreasSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    act: int
    area_level: int
    area_mods: list[str]
    bosses: list[str]
    connections: list[str]
    environment: str | None = None
    has_waypoint: bool
    id: str
    is_town: bool
    loading_screens: list[str]
    name: str
    tags: list[str]
    topologies: list[Topology] | None = None
    area_type_tags: list[str] | None = None
    parent_town: str | None = None
    packs: list[Pack] | None = None
    terrain_plugins: str | None = None


class Model(RootModel[dict[str, WorldAreasSchemaValue]]):
    root: dict[str, WorldAreasSchemaValue]
