default_language_version:
  python: python3
repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: datamodel-code-generator
        name: update models
        files: ^RePoE/schema
        language: system
        entry: poetry run ./datamodel-codegen.sh
