name: Check patch version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.VERSION_COMMIT_PAT }}
    - name: get version
      run: curl https://raw.githubusercontent.com/poe-tool-dev/latest-patch-version/main/latest.txt > version.txt
      working-directory: RePoE
    - name: commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update patch version"
