name: Check patch version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4.2.2
      with:
        token: ${{ secrets.VERSION_COMMIT_PAT }}
    - name: get version
      run: |
        curl --fail 'https://ggpk.exposed/version?poe=1' | sed -r 's|.*/([0-9](\.[0-9]+)+)/$|\1|' > RePoE/version.txt
        curl --fail 'https://ggpk.exposed/version?poe=2' | sed -r 's|.*/([0-9](\.[0-9]+)+)/$|\1|' > RePoE/version2.txt
    - name: get schema hash
      run: git ls-remote https://github.com/poe-tool-dev/dat-schema.git refs/heads/main > RePoE/schema.txt
    - name: set version
      id: set-version
      run: echo "version=$(cat RePoE/version.txt) / $(cat RePoE/version2.txt)" >> "$GITHUB_OUTPUT"
    - name: commit changes
      uses: stefanzweifel/git-auto-commit-action@v5.2.0
      with:
        commit_message: "Version ${{ steps.set-version.outputs.version }}"
