name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: checkout pypoe
      uses: actions/checkout@v3
      with:
        repository: lvlvllvlvllvlvl/PyPoE
        path: PyPoE
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: install pypoe
      run: pip install -e .
      working-directory: PyPoE
    - name: install repoe
      run: pip install -e .
    - name: run export
      run: python run_parser.py all -f "http://patchcdn.pathofexile.com/$(<version.txt)/"
      working-directory: RePoE
    - name: commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[skip ci] Automated export"
