name: Run data export

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: checkout pypoe
      uses: actions/checkout@v3
      with:
        repository: lvlvllvlvllvlvl/PyPoE
        path: PyPoE
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip    
    - name: install requirements
      run: pip install -r requirements.txt
    - name: install pypoe
      run: pip install -e .
      working-directory: PyPoE
    - name: install repoe
      run: pip install -e .
    - name: run export
      run: python run_parser.py all -f "http://patchcdn.pathofexile.com/$(<version.txt)/"
      working-directory: RePoE
    - name: generate index.html
      run: tree -H '.' --filesfirst --noreport --charset utf-8 -o index.html
      working-directory: RePoE/data/
    - name: upload gh-pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: RePoE/data/
    - name: commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[skip ci] Automated export"

  deploy:
    runs-on: ubuntu-latest

    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: deploy gh-pages
        id: deployment
        uses: actions/deploy-pages@v1
